version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_2207Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_2207.integrations:test
  packages:
  - name: Kvv_2207Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.7
